import '../styles/main.css';
import { initScribbles } from './scribbles.js';
import { initHeroPen } from './hero-pen.js';
import { initClocks } from './clocks.js';
import { initLogomark } from './logomark.js';
import { initBuilding } from './building.js';
import { initMap } from './map.js';
import { initGraphs } from './graphs.js';
initScribbles();
initHeroPen();
initClocks();
initLogomark();
initBuilding();
initMap();
initGraphs();
